// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDli81bJlkxHKDHcveISEm-V45MDjshWCY',
    appId: '1:215023104127:web:00fe1c79d7e7754f0f4f4a',
    messagingSenderId: '215023104127',
    projectId: 'doros-8ee0c',
    authDomain: 'doros-8ee0c.firebaseapp.com',
    storageBucket: 'doros-8ee0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR_MO6tnKMX3gE2a0wmN805Af23GvmMxo',
    appId: '1:215023104127:android:76a51c9bc7c35e2c0f4f4a',
    messagingSenderId: '215023104127',
    projectId: 'doros-8ee0c',
    storageBucket: 'doros-8ee0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY6mGP6-RcSJ4D811KWsOJOQBpXigaS7Y',
    appId: '1:215023104127:ios:1249df4e314cb5540f4f4a',
    messagingSenderId: '215023104127',
    projectId: 'doros-8ee0c',
    storageBucket: 'doros-8ee0c.appspot.com',
    iosClientId: '215023104127-rs1t2g3cmdoq6ckv2db39r3ss99bcql3.apps.googleusercontent.com',
    iosBundleId: 'com.example.doros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY6mGP6-RcSJ4D811KWsOJOQBpXigaS7Y',
    appId: '1:215023104127:ios:1249df4e314cb5540f4f4a',
    messagingSenderId: '215023104127',
    projectId: 'doros-8ee0c',
    storageBucket: 'doros-8ee0c.appspot.com',
    iosClientId: '215023104127-rs1t2g3cmdoq6ckv2db39r3ss99bcql3.apps.googleusercontent.com',
    iosBundleId: 'com.example.doros',
  );
}
